# Generated by Django 5.1.4 on 2024-12-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='clinics',
            field=models.ManyToManyField(blank=True, default='Individual', related_name='doctors', to='booking.clinic'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='end_time',
            field=models.TimeField(default='09:30:00'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='start_time',
            field=models.TimeField(default='09:00:00'),
        ),
    ]
