# Generated by Django 5.1.4 on 2024-12-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_doctor_clinics_alter_doctor_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='specialty_offered',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
