# Generated by Django 5.1.4 on 2024-12-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_patient_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='clinics',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='booking.clinic'),
        ),
    ]
