# Generated by Django 5.1.4 on 2024-12-15 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_doctor_clinics'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
