# Generated by Django 5.1.4 on 2024-12-15 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_appointment_created_at_appointment_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='clinic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booking.clinic'),
        ),
    ]
