# Generated by Django 5.1.4 on 2024-12-24 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_timeslot_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslotgroup',
            old_name='date',
            new_name='appointment_date',
        ),
        migrations.AddField(
            model_name='timeslotgroup',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
